CREATE DATABASE store;

USE store;

CREATE TABLE promocode (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(6) NOT NULL
);

CREATE TABLE image (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE category (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	id_image INT DEFAULT 1,
	FOREIGN KEY (id_image) REFERENCES image(id)
);

CREATE TABLE product (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	info TEXT NOT NULL,
	id_image INT DEFAULT 1,
	id_category INT NOT NULL,
	price INT NOT NULL CHECK (price >= 0),
	sale INT DEFAULT 0 CHECK (sale >= 0 AND sale <= 100),
	price_promocode INT NOT NULL CHECK (price_promocode >= 0),
	FOREIGN KEY (id_image) REFERENCES image(id),
	FOREIGN KEY (id_category) REFERENCES category(id)
);

CREATE TABLE product_category (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_product INT NOT NULL,
	id_category INT NOT NULL,
	FOREIGN KEY (id_product) REFERENCES product(id),
	FOREIGN KEY (id_category) REFERENCES category(id)
);

CREATE TABLE product_image (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_product INT NOT NULL,
	id_image INT DEFAULT 0,
	FOREIGN KEY (id_product) REFERENCES product(id),
	FOREIGN KEY (id_image) REFERENCES image(id)
);

CREATE TABLE warehouse (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_product INT NOT NULL,
	count INT DEFAULT 0 CHECK (count >= 0),
	FOREIGN KEY (id_product) REFERENCES product(id)
);

INSERT INTO promocode(name) VALUES
('POWERS'),
('PROMO2'),
('SALE50');

INSERT INTO image(name) VALUES
('product_default.png'),
('product_1.png'),
('product_1_1.png'),
('product_1_2.png'),
('product_1_3.png'),
('product_2.png'),
('product_2_1.png'),
('product_2_2.png'),
('product_2_3.png'),
('product_3.png'),
('product_3_1.png'),
('product_3_2.png'),
('product_3_3.png'),
('product_4.png'),
('product_4_1.png'),
('product_4_2.png'),
('product_4_3.png'),
('product_5.png'),
('product_5_1.png'),
('product_5_2.png'),
('product_5_3.png'),
('product_6.png'),
('product_6_1.png'),
('product_6_2.png'),
('product_6_3.png'),
('product_7.png'),
('product_7_1.png'),
('product_7_2.png'),
('product_7_3.png'),
('product_8.png'),
('product_8_1.png'),
('product_8_2.png'),
('product_8_3.png'),
('product_9.png'),
('product_9_1.png'),
('product_9_2.png'),
('product_9_3.png'),
('product_10.png'),
('product_10_1.png'),
('product_10_2.png'),
('product_10_3.png'),
('product_11.png'),
('product_11_1.png'),
('product_11_2.png'),
('product_11_3.png'),
('product_12.png'),
('product_12_1.png'),
('product_12_2.png'),
('product_12_3.png'),
('product_13.png'),
('product_13_1.png'),
('product_13_2.png'),
('product_13_3.png'),
('product_14.png'),
('product_14_1.png'),
('product_14_2.png'),
('product_14_3.png'),
('product_15.png'),
('product_15_1.png'),
('product_15_2.png'),
('product_15_3.png'),
('category_1.png'),
('category_2.png'),
('category_3.png'),
('category_4.png'),
('category_5.png'),
('category_6.png'),
('category_7.png'),
('category_8.png'),
('category_9.png'),
('category_10.png'),
('category_11.png');



INSERT INTO category(name, id_image) VALUES
('Одежда',
(SELECT image.id FROM image WHERE image.name = 'category_1.png')),
('Мужская одежда',
(SELECT image.id FROM image WHERE image.name = 'category_2.png')),
('Женская одежда',
(SELECT image.id FROM image WHERE image.name = 'category_3.png')),
('Рубашки',
(SELECT image.id FROM image WHERE image.name = 'category_4.png')),
('Футболки',
(SELECT image.id FROM image WHERE image.name = 'category_5.png')),
('Майки',
(SELECT image.id FROM image WHERE image.name = 'category_6.png')),
('Джинсы',
(SELECT image.id FROM image WHERE image.name = 'category_7.png')),
('Брюки',
(SELECT image.id FROM image WHERE image.name = 'category_8.png')),
('Платья',
(SELECT image.id FROM image WHERE image.name = 'category_9.png')),
('Шорты',
(SELECT image.id FROM image WHERE image.name = 'category_10.png')),
('Куртки',
(SELECT image.id FROM image WHERE image.name = 'category_11.png'));

INSERT INTO product(name, info, id_image, id_category, price, sale, price_promocode) VALUES
('Vittoria Vicci', 
'Состав: Хлопок - 97%, Эластан - 3%. Размер товара на модели: S INT. Параметры модели: 84-61-91. Рост модели на фото: 180. Длина: 79 см. Длина рукава: 60 см. Сезон: мульти. Цвет: белый',
(SELECT image.id FROM image WHERE image.name = 'product_1.png'),
(SELECT category.id FROM category WHERE category.name = 'Рубашки'), 
4690, 45, 1300),
('A.Karina', 
'Состав: Вискоза - 80%, Полиэстер - 20% Материал подкладки: Без подкладки Сезон: мульти Цвет: синий Узор: горох Гарантийный период: 30 дней Страна производства: Россия Застежка: пуговицы',
(SELECT image.id FROM image WHERE image.name = 'product_2.png'),
(SELECT category.id FROM category WHERE category.name = 'Платья'), 
6490, 25, 4000),
('Ostin', 
'Куртка, утепленная синтепоном, выполнена из гладкого текстиля. Модель прямого кроя. Детали: застежка на молнию, 2 внешних кармана, несъемный регулируемый трикотажный капюшон, трикотажные резинки на манжетах и по низу изделия, ветрозащитная планка.',
(SELECT image.id FROM image WHERE image.name = 'product_3.png'),
(SELECT category.id FROM category WHERE category.name = 'Куртки'), 
4499, 55, 1500),
('Pull&Bear', 
'Товары Pull&Bear нельзя примерить и они доставляются отдельным заказом. Состав: Полиэстер - 62%, Вискоза - 33%, Эластан - 5% Материал подкладки: без подкладки Утеплитель: без утеплителя',
(SELECT image.id FROM image WHERE image.name = 'product_4.png'),
(SELECT category.id FROM category WHERE category.name = 'Брюки'), 
2999, 0, 2200),
('Ostin Куртка', 
'Утепленная куртка выполнена из стеганого текстиля с искусственным наполнителем. Детали: застежка-кнопки, воротник-стойка, несъемный капюшон, два внешних кармана.',
(SELECT image.id FROM image WHERE image.name = 'product_5.png'),
(SELECT category.id FROM category WHERE category.name = 'Куртки'), 
3999, 10, 2000),
('Envylab', 
'Состав: Хлопок - 95%, Лайкра - 5% Материал подкладки: без подкладки Размер товара на модели: L Параметры модели: 105-84-97 Рост модели на фото: 186',
(SELECT image.id FROM image WHERE image.name = 'product_6.png'),
(SELECT category.id FROM category WHERE category.name = 'Футболки'), 
1120, 29, 500),
('Marks & Spencer', 
'Состав: Хлопок - 100% Размер товара на модели: 32/33 JEANS Параметры модели: 100-85-99 Рост модели на фото: 189 Высота: 27 см Длина по внутреннему шву: 85 см',
(SELECT image.id FROM image WHERE image.name = 'product_7.png'),
(SELECT category.id FROM category WHERE category.name = 'Джинсы'), 
3499, 0, 3499),
('Under Armour', 
'Состав: Полиэстер - 100% Сезон: мульти Цвет: черный Узор: однотонный Вид спорта: бег Страна производства: Иордания',
(SELECT image.id FROM image WHERE image.name = 'product_8.png'),
(SELECT category.id FROM category WHERE category.name = 'Шорты'), 
2899, 0, 2500),
('Lyle & Scott', 
'Состав: Хлопок - 100% Размер товара на модели: 32/33 JEANS Параметры модели: 100-85-99 Рост модели на фото: 189 Высота: 27 см Длина по внутреннему шву: 85 см',
(SELECT image.id FROM image WHERE image.name = 'product_9.png'),
(SELECT category.id FROM category WHERE category.name = 'Куртки'), 
3499, 0, 3499),
('Брюки спортивные Jets', 
'Состав: Хлопок - 95%, Лайкра - 5% Материал подкладки: без подкладки Утеплитель: без утеплителя Размер товара на модели: L Параметры модели: 105-84-97 Рост модели на фото: 186 Длина по внутреннему шву: 78 см',
(SELECT image.id FROM image WHERE image.name = 'product_10.png'),
(SELECT category.id FROM category WHERE category.name = 'Брюки'), 
4271, 41, 2490),
('Elementarno', 
'Состав: Хлопок - 100% Длина: 75 см Сезон: мульти Цвет: белый Узор: однотонный Гарантийный период: не установлен Страна производства: Узбекистан',
(SELECT image.id FROM image WHERE image.name = 'product_11.png'),
(SELECT category.id FROM category WHERE category.name = 'Майки'), 
699, 10, 500),
('Reebok Майка', 
'Состав: Хлопок - 100% Размер товара на модели: S INT Параметры модели: 100-85-99 Рост модели на фото: 189 Длина: 68 см Сезон: мульти Цвет: черный Узор: рисунки и надписи',
(SELECT image.id FROM image WHERE image.name = 'product_12.png'),
(SELECT category.id FROM category WHERE category.name = 'Майки'), 
1999, 0, 1999),
('Polo Ralph Lauren Платье', 
'Состав: Хлопок - 100% Размер товара на модели: S INT Параметры модели: 100-85-99 Рост модели на фото: 189 Длина: 68 см Сезон: мульти Цвет: черный Узор: рисунки и надписи',
(SELECT image.id FROM image WHERE image.name = 'product_13.png'),
(SELECT category.id FROM category WHERE category.name = 'Платья'), 
1999, 0, 1999),
('Polo Ralph Lauren', 
'Состав: Хлопок - 100% Размер товара на модели: M INT Параметры модели: 95-73-95 Рост модели на фото: 189 Длина: 77 см Длина рукава: 65 см Сезон: мульти Цвет: голубой',
(SELECT image.id FROM image WHERE image.name = 'product_14.png'),
(SELECT category.id FROM category WHERE category.name = 'Рубашки'), 
12000, 0, 12000),
('Oodji', 
'Состав: Хлопок 100% Материал подкладки: без подкладки Размер товара на модели: М Параметры модели: 100-83-100 Рост модели на фото: 189 Сезон: мульти Цвет: серый Узор: однотонный',
(SELECT image.id FROM image WHERE image.name = 'product_15.png'),
(SELECT category.id FROM category WHERE category.name = 'Рубашки'), 
1999, 50, 1400);

INSERT INTO product_category(id_product, id_category) VALUES
(1, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(1, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(2, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(2, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(3, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(3, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(4, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(4, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(5, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(5, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(6, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(6, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(7, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(7, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(8, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(8, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(9, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(9, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(10, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(10, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(11, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(11, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(12, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(12, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(13, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(13, (SELECT category.id FROM category WHERE category.name = 'Женская одежда')),
(14, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(14, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда')),
(15, (SELECT category.id FROM category WHERE category.name = 'Одежда')),
(15, (SELECT category.id FROM category WHERE category.name = 'Мужская одежда'));

INSERT INTO product_image(id_product, id_image) VALUES
(1, (SELECT image.id FROM image WHERE image.name = 'product_1_1.png')),
(1, (SELECT image.id FROM image WHERE image.name = 'product_1_2.png')),
(1, (SELECT image.id FROM image WHERE image.name = 'product_1_3.png')),
(2, (SELECT image.id FROM image WHERE image.name = 'product_2_1.png')),
(2, (SELECT image.id FROM image WHERE image.name = 'product_2_2.png')),
(2, (SELECT image.id FROM image WHERE image.name = 'product_2_3.png')),
(3, (SELECT image.id FROM image WHERE image.name = 'product_3_1.png')),
(3, (SELECT image.id FROM image WHERE image.name = 'product_3_2.png')),
(3, (SELECT image.id FROM image WHERE image.name = 'product_3_3.png')),
(4, (SELECT image.id FROM image WHERE image.name = 'product_4_1.png')),
(4, (SELECT image.id FROM image WHERE image.name = 'product_4_2.png')),
(4, (SELECT image.id FROM image WHERE image.name = 'product_4_3.png')),
(5, (SELECT image.id FROM image WHERE image.name = 'product_5_1.png')),
(5, (SELECT image.id FROM image WHERE image.name = 'product_5_2.png')),
(5, (SELECT image.id FROM image WHERE image.name = 'product_5_3.png')),
(6, (SELECT image.id FROM image WHERE image.name = 'product_6_1.png')),
(6, (SELECT image.id FROM image WHERE image.name = 'product_6_2.png')),
(6, (SELECT image.id FROM image WHERE image.name = 'product_6_3.png')),
(7, (SELECT image.id FROM image WHERE image.name = 'product_7_1.png')),
(7, (SELECT image.id FROM image WHERE image.name = 'product_7_2.png')),
(7, (SELECT image.id FROM image WHERE image.name = 'product_7_3.png')),
(8, (SELECT image.id FROM image WHERE image.name = 'product_8_1.png')),
(8, (SELECT image.id FROM image WHERE image.name = 'product_8_2.png')),
(8, (SELECT image.id FROM image WHERE image.name = 'product_8_3.png')),
(9, (SELECT image.id FROM image WHERE image.name = 'product_9_1.png')),
(9, (SELECT image.id FROM image WHERE image.name = 'product_9_2.png')),
(9, (SELECT image.id FROM image WHERE image.name = 'product_9_3.png')),
(10, (SELECT image.id FROM image WHERE image.name = 'product_10_1.png')),
(10, (SELECT image.id FROM image WHERE image.name = 'product_10_2.png')),
(10, (SELECT image.id FROM image WHERE image.name = 'product_10_3.png')),
(11, (SELECT image.id FROM image WHERE image.name = 'product_11_1.png')),
(11, (SELECT image.id FROM image WHERE image.name = 'product_11_2.png')),
(11, (SELECT image.id FROM image WHERE image.name = 'product_11_3.png')),
(12, (SELECT image.id FROM image WHERE image.name = 'product_12_1.png')),
(12, (SELECT image.id FROM image WHERE image.name = 'product_12_2.png')),
(12, (SELECT image.id FROM image WHERE image.name = 'product_12_3.png')),
(13, (SELECT image.id FROM image WHERE image.name = 'product_13_1.png')),
(13, (SELECT image.id FROM image WHERE image.name = 'product_13_2.png')),
(13, (SELECT image.id FROM image WHERE image.name = 'product_13_3.png')),
(14, (SELECT image.id FROM image WHERE image.name = 'product_14_1.png')),
(14, (SELECT image.id FROM image WHERE image.name = 'product_14_2.png')),
(14, (SELECT image.id FROM image WHERE image.name = 'product_14_3.png')),
(15, (SELECT image.id FROM image WHERE image.name = 'product_15_1.png')),
(15, (SELECT image.id FROM image WHERE image.name = 'product_15_2.png')),
(15, (SELECT image.id FROM image WHERE image.name = 'product_15_3.png'));

INSERT INTO warehouse(id_product, count) VALUES
(1, 100),
(2, 50),
(3, 10),
(4, 90),
(5, 100),
(6, 100),
(7, 11),
(8, 7),
(9, 45),
(10, 10),
(11, 26),
(12, 5),
(13, 20),
(14, 62),
(15, 73);
